# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  boot.initrd.luks.devices."cryptmain" = {
    device = "/dev/disk/by-uuid/95822fbd-bcfb-47f2-91a6-ed3eef0d2651";
    preLVM = true;
    allowDiscards = true;
  };

  fileSystems."/" = {
    device = "/dev/mapper/vg_main-lv_nixos";
    fsType = "btrfs";
    options = ["subvol=@" "noatime" "compress=zstd:3" "space_cache=v2" "autodefrag"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/vg_main-lv_nixos";
    fsType = "btrfs";
    options = ["subvol=@home" "noatime" "compress=zstd:3" "space_cache=v2" "autodefrag"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/vg_main-lv_nixos";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "compress=zstd:3" "space_cache=v2" "autodefrag"];
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/vg_main-lv_nixos";
    fsType = "btrfs";
    options = ["subvol=@log" "noatime" "compress=zstd:3" "space_cache=v2" "autodefrag"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/mapper/vg_main-lv_nixos";
    fsType = "btrfs";
    options = ["subvol=@snapshots" "noatime" "compress=zstd:3" "space_cache=v2" "autodefrag"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/a1f1e1c0-66f1-47d0-9d53-290e43ecbc78";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/513E-346B";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/7c768661-c4ce-4c8d-bca5-6aa93b3e1a94";
      priority = 10;
      randomEncryption = {
        enable = true;
        allowDiscards = true;
      };
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
